  syntax = "proto3";

  package auth;

  option go_package = "pixly.auth.v1;authv1";

  service Auth {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Refresh(RefreshRequest) returns (RefreshResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
    rpc ResendVerification(ResendVerificationRequest) returns(ResendVerificationResponse);
  }

  message ResendVerificationRequest {
    string email = 1;
  }

  message ResendVerificationResponse {
    bool success = 1;
  }

  message GetUserRequest {
    string id = 1;
  }

  message GetUserResponse {
    string id = 1;
    string email = 2;
    string username = 3;
  }

  message RefreshRequest{
    string refresh_token = 1;
  }

  message RefreshResponse{
    string access_token = 1;
    string refresh_token = 2;
  }

  message LoginRequest {
    string email = 1;
    string password = 2;
  }

  message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
  }

  message RegisterRequest {
    string email = 1;
    string username = 2;
    string password = 3;
  }

  message RegisterResponse {
    bool success = 1;
  }

  message VerifyEmailRequest {
    string code = 1;
  }

  message VerifyEmailResponse {
    bool success = 1;
  }
