syntax = "proto3";

package auth;

option go_package = "pixly.auth.v1;authv1";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);
}

message RegisterRequest {
  string email = 1;
  string username = 2;
  string password = 3;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
}

message VerifyEmailRequest {
  string code = 1;
}

message VerifyEmailResponse {
  bool success = 1;
  string message = 2;
}
