// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate by email and password. Returns access_token and TTLs. Refresh token is set in httpOnly cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Email and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "412": {
                        "description": "USER_NOT_VERIFIED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Issue new access token using refresh token from httpOnly cookie (or optional body). New refresh token is set in cookie. Returns access_token and TTLs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token (optional if sent via cookie)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Missing refresh token",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "SESSION_NOT_FOUND, SESSION_EXPIRED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Register a new user. A verification email is sent to the given address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST, INVALID_EMAIL, INVALID_USERNAME, INVALID_PASSWORD",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "USER_ALREADY_EXISTS, USERNAME_TAKEN",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/resend-verification": {
            "post": {
                "description": "Resend the verification email to the given address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Resend verification email",
                "parameters": [
                    {
                        "description": "User email",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.ResendVerificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "USER_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify": {
            "post": {
                "description": "Confirm email using the token from the verification email (query param token).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification token from email",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "INVALID_VERIFICATION_CODE",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Returns service status and current time in RFC3339.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_healthcheck.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return the authenticated user. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_auth.MeResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pixelart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new pixelart for the authenticated user. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "art"
                ],
                "summary": "Save pixelart",
                "parameters": [
                    {
                        "description": "Pixelart data (title, palette, pixels, width, height)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_art.SavePixelartRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_art.SavePixelartResponse"
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST, invalid body or validation",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "PIXELART_CONFLICT",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pixelart/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a specific pixelart by ID for the authenticated user. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "art"
                ],
                "summary": "Get pixelart by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pixelart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_art.GetUserPixelartResponse"
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "PIXELART_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a pixelart by ID. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "art"
                ],
                "summary": "Delete pixelart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pixelart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "PIXELART_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the canvas of an existing pixelart. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "art"
                ],
                "summary": "Update pixelart canvas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pixelart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Canvas data (palette, pixels, width, height)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_art.UpdateCanvasRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "BAD_REQUEST",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "PIXELART_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/pixelarts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of all pixelart previews for the authenticated user. Requires Authorization: Bearer \u0026lt;access_token\u0026gt;.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "art"
                ],
                "summary": "Get user pixelarts previews",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infra_api_handlers_art.GetUserPreviewsResponse"
                        }
                    },
                    "401": {
                        "description": "UNAUTHENTICATED",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "INTERNAL_ERROR",
                        "schema": {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.Code": {
            "type": "string",
            "enum": [
                "BAD_REQUEST",
                "INVALID_EMAIL",
                "INVALID_USERNAME",
                "INVALID_PASSWORD",
                "INVALID_VERIFICATION_CODE",
                "USER_ALREADY_EXISTS",
                "USERNAME_TAKEN",
                "USER_NOT_FOUND",
                "USER_NOT_VERIFIED",
                "USER_ALREADY_VERIFIED",
                "UNAUTHENTICATED",
                "SESSION_NOT_FOUND",
                "SESSION_EXPIRED",
                "INTERNAL_ERROR",
                "PIXELART_NOT_FOUND",
                "PIXELART_CONFLICT"
            ],
            "x-enum-varnames": [
                "BadRequest",
                "InvalidEmail",
                "InvalidUsername",
                "InvalidPassword",
                "InvalidVerificationCode",
                "UserAlreadyExists",
                "UsernameTaken",
                "UserNotFound",
                "UserNotVerified",
                "UserAlreadyVerified",
                "Unauthenticated",
                "SessionNotFound",
                "SessionExpired",
                "InternalError",
                "PixelartNotFound",
                "PixelartConflict"
            ]
        },
        "github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.Code"
                        }
                    ],
                    "example": "BAD_REQUEST"
                },
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        },
        "github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_1ncrease0_pixly_services_gateway_internal_infra_api_apierr.ErrorDetail"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                }
            }
        },
        "internal_infra_api_handlers_art.GetUserPixelartResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 16
                },
                "image_url": {
                    "type": "string",
                    "example": "https://minio.example.com/pixelarts/abc.png"
                },
                "palette": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "#000000",
                        "#ffffff"
                    ]
                },
                "pixels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "My pixel art"
                },
                "width": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "internal_infra_api_handlers_art.GetUserPreviewsResponse": {
            "type": "object",
            "properties": {
                "previews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infra_api_handlers_art.PreviewResponse"
                    }
                }
            }
        },
        "internal_infra_api_handlers_art.PreviewResponse": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string",
                    "example": "https://minio.example.com/pixelarts/abc.png"
                },
                "pixelart_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "title": {
                    "type": "string",
                    "example": "My pixel art"
                }
            }
        },
        "internal_infra_api_handlers_art.SavePixelartRequest": {
            "type": "object",
            "required": [
                "height",
                "palette",
                "pixels",
                "title",
                "width"
            ],
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 16
                },
                "palette": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "#000000",
                        "#ffffff"
                    ]
                },
                "pixels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "My pixel art"
                },
                "width": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "internal_infra_api_handlers_art.SavePixelartResponse": {
            "type": "object",
            "properties": {
                "pixelart_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_infra_api_handlers_art.UpdateCanvasRequest": {
            "type": "object",
            "required": [
                "height",
                "palette",
                "pixels",
                "width"
            ],
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 16
                },
                "palette": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "#000000",
                        "#ffffff"
                    ]
                },
                "pixels": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "width": {
                    "type": "integer",
                    "example": 16
                }
            }
        },
        "internal_infra_api_handlers_auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "internal_infra_api_handlers_auth.MeResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "internal_infra_api_handlers_auth.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Email verified successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_infra_api_handlers_auth.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "internal_infra_api_handlers_auth.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securePassword123"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "internal_infra_api_handlers_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Registration successful, verification email sent"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_infra_api_handlers_auth.ResendVerificationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "internal_infra_api_handlers_auth.TokenPairResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "access_ttl_sec": {
                    "type": "integer",
                    "example": 900
                },
                "refresh_ttl_sec": {
                    "type": "integer",
                    "example": 2592000
                }
            }
        },
        "internal_infra_api_handlers_healthcheck.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Pixly Gateway API",
	Description:      "Pixly gateway HTTP API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
