env: "local"

grpc:
  port: 50052

postgres:
  dsn: "postgres://postgres:123456@localhost:5433/art?sslmode=disable"

minio:
  endpoint: "localhost:9000"
  access_key: "rootname"
  secret_key: "password123"
  use_ssl: false
  buckets: ["pixelarts"]
  presign_ttl: 1h