name: Go

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-service-auth:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./services/auth
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Download dependencies
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod download
          go mod tidy

      - name: Build
        working-directory: ${{ matrix.work_dir }}
        run: |
          go build -v ./cmd/auth

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        working-directory: ${{ matrix.work_dir }}
        run: |
          golangci-lint run

  build-service-notification:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./services/notification
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Download dependencies
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod download
          go mod tidy

      - name: Build
        working-directory: ${{ matrix.work_dir }}
        run: |
          go build -v ./cmd/notification

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        working-directory: ${{ matrix.work_dir }}
        run: |
          golangci-lint run

  build-service-gateway:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./services/gateway
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'

      - name: Download dependencies
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod download
          go mod tidy

      - name: Build
        working-directory: ${{ matrix.work_dir }}
        run: |
          go build -v ./cmd/gateway

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        working-directory: ${{ matrix.work_dir }}
        run: |
          golangci-lint run